from enum import Enum


class EventType(Enum):
    ON_ATTACK = 1
    RAW_INPUT_KEY = 2
    RAW_INPUT_MOUSE = 3
    ENTITY_SELECTED = 4
    LOGIC_COMBAT_RESOLVED = 5
    LOGIC_MATCH_SETUP_COMPLETE = 6
    LOGIC_TURN_STARTED = 7
    ACTION_PAUSE_GAME = 8
