from typing import Protocol


class EntityCard(Protocol):
    def attack(self, target: EntityCard) -> None: ...
    def heal(self) -> int: ...

    @property
    def can_attack(self) -> bool: ...
    @property
    def has_attacked(self) -> bool: ...
    @property
    def id(self) -> int: ...
