from typing import Protocol, runtime_checkable


@runtime_checkable
class EntityCard(Protocol):
    def attack(self, target: "EntityCard") -> None: ...
    def take_damage(self, amount: int) -> int: ...
    def heal(self, amount: int) -> int: ...
    def reset_turn_state(self) -> None: ...

    @property
    def can_attack(self) -> bool: ...
    @property
    def current_health(self) -> int: ...
    @property
    def has_attacked(self) -> bool: ...
    @property
    def is_alive(self) -> bool: ...
    @property
    def id(self) -> int: ...
    @property
    def attack_damage(self) -> int: ...
    @property
    def gold_profit(self) -> int: ...
